apiVersion: v1
kind: Service
metadata:
  name: tornado-service
  labels:
    app: tornado
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: tornado
  type: LoadBalancer
  loadBalancerIP: 192.168.59.3
  ports:
    - protocol: TCP
      name: http
      port: 8888
      targetPort: 8888
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornado-deployment
  labels:
    app: tornado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tornado
  template:
    metadata:
      labels:
        app: tornado
    spec:
      containers:
        - name: tornado
          image: image_tornado_0
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
